version: '3.8'

services:
  db:
    image: postgres:16.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    command: gunicorn cloudtalents.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/opt/app/cloudtalents/static
      - media_volume:/opt/app/media
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000

  nginx:
    build: ./nginx
    env_file:
      - ./.env
    ports:
      - "80:80"
    volumes:
      - static_volume:/opt/app/cloudtalents/static
      - media_volume:/opt/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
