on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.ARN_IAM_ROLE }}
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: init
        run: |
          cd terraform
          terraform init

      - id: apply
        run: |
          cd terraform
          terraform apply
