on:
  push:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.ARN_IAM_ROLE }}
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - id: apply
        run: terraform apply
